# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'
- script: |
    npm install --global yarn
  displayName: "Install Yarn"
- script: |
    node -v
    yarn -v
  displayName: "Print versions"
#- script: |
#    yarn --frozen-lockfile
#  displayName: "Install dependencies"
- script: |
    del "ember-try*.tgz" >nul 2>&1
    echo npm pack
    npm pack
  displayName: "Build package"
- script: |
    set ran=%RANDOM%
    echo move package
    move "ember-try*.tgz" "ember-try-%ran%.tgz"
    echo yarn install
    cd smoke-test-app && yarn upgrade "ember-try@../ember-try-%ran%.tgz" && yarn install
  displayName: "Install smoke-test deps"
- bash: |
    cd smoke-test-app && node_modules/.bin/ember try:each 
  failOnStderr: true
  displayName: "Run smoke test"
