# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@1.0.1

commands:
  npm-smoke-test:
    steps:
      - run: node --version
      - run: npm version
      - checkout
      - node/with-cache:
          steps:
            - run: npm run smoke-test

  yarn-smoke-test:
    steps:
      - run: node --version
      - run: npm version
      - checkout
      - node/install-yarn
      - node/with-cache:
          steps:
            - run: yarn smoke-test-yarn

  node-test:
    steps:
      - run: node --version
      - run: npm version
      - checkout
      - node/install-yarn
      - node/with-cache:
          steps:
            - run:
                name: Install dependencies
                command: yarn install
            - run: yarn node-test-with-coverage

  floating-deps:
    steps:
      - run: node --version
      - run: npm version
      - checkout
      - node/install-yarn
      - node/with-cache:
          steps:
            - run:
                name: Install dependencies (floating)
                command: yarn install --no-lockfile
            - run: yarn node-test


jobs:
  lint:
    docker:
      - image: circleci/node:lts
    steps:
      - run: node --version
      - run: npm version
      - checkout
      - node/install-yarn
      - node/with-cache:
          steps:
            - run:
                name: Install dependencies
                command: yarn install
            - run:
                name: Lint files
                command: yarn lint

  node-v8-smoke-test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - npm-smoke-test

  node-v8-yarn-smoke-test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - yarn-smoke-test

  node-lts-smoke-test:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - npm-smoke-test

  yarn-lts-smoke-test:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - yarn-smoke-test

  node-current-smoke-test:
    docker:
      - image: circleci/node:current-browsers
    steps:
      - npm-smoke-test

  yarn-current-smoke-test:
    docker:
      - image: circleci/node:current-browsers
    steps:
      - yarn-smoke-test

  all-commands-smoke-test:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - run: node --version
      - run: npm version
      - checkout
      - node/with-cache:
          steps:
            - run: npm run client-test

  node-lts-test:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - node-test

  floating-deps:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - floating-deps

  deploy:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - run: node --version
      - run: npm version
      - checkout
      - node/install-yarn
      - node/with-cache:
          steps:
            - run:
                name: Install dependencies
                command: yarn install
      - run: yarn global add auto-dist-tag
      - run: auto-dist-tag --write
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - floating-deps
  test-and-deploy:
    jobs:
      - lint
      - node-lts-test
      - floating-deps
      - node-v8-smoke-test:
          requires:
            - lint
            - node-lts-test
      - node-v8-yarn-smoke-test:
          requires:
            - lint
            - node-lts-test
      - node-lts-smoke-test:
          requires:
            - lint
            - node-lts-test
      - yarn-lts-smoke-test:
          requires:
            - lint
            - node-lts-test
      - node-current-smoke-test:
          requires:
            - lint
            - node-lts-test
      - yarn-current-smoke-test:
          requires:
            - lint
            - node-lts-test
      - all-commands-smoke-test:
          requires:
            - lint
            - node-lts-test
      - deploy:
          requires:
            - all-commands-smoke-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

