version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"

  - package_manager: "javascript"
    directory: "/smoke-test-app"
    update_schedule: "weekly"
